// Auto-generated by GitHub Action. Do not edit manually.
// The values below are overwritten at build time by .github/workflows/main.yml.
// If you see "manual-build" / "local" in the app console, you're on a locally built SDK.
public let SDK_BUILD_TIMESTAMP = "manual-build"
public let SDK_BUILD_COMMIT = "local"
